config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    blog.update(blog_params)
    redirect_to blogs_path
  end

  def new
    @blog = Blog.new
  end

  def create
    blog = Blog.create(blog_params)
    redirect_to blogs_path
  end

  def destroy
    Blog.destroy(params[:id])
    redirect_to blogs_path
  end

  def admin
  end

  private

  def blog_params
    params.require(:blog).permit( :title, :tagline, :message,
    :country, :url_model, :header_image )
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @blogs = Blog.order('created_at ASC')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_new_blog.html.erb
<%= form_for @blog do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :header_image %>:
  <%= f.text_field :header_image %><br />

  <%= f.label :tagline %>:
  <%= f.text_field :tagline %><br />

  <%= f.label :message %>:
  <%= f.cktext_area :message %><br />

  <%= f.label :country %>:
  <%= f.text_field :country %><br />

  <%= f.label :url_model %>:
  <%= f.text_field :url_model %><br />

  <%= f.submit %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit <%= @blog.title %></h1>

<h6><%= link_to "Back to your posts", blogs_path %></h6>
<%= render 'new_blog' %>

app/views/blogs/index.html.erb
<h1>Your Posts</h1>

<h6><%= link_to "Create a New Post", new_blog_path %></h6>
<table>
 <thead>
   <tr>
       <th>Name</th>
       <th>Tagline</th>
       <th>Country</th>
       <th>Edit</th>
       <th>Delete</th>
   </tr>
 </thead>

 <tbody>
   <% @blogs.each do |blog| %>
  <tr>
    <td><%=  blog.title %></td>
    <td><%=  blog.tagline %></td>
    <td><%=  blog.country %></td>
    <td><%=  link_to "Edit", edit_blog_path(blog), class: "waves-effect waves-light btn modal-trigger blue lighten-2" %></td>
    <td>
      <a class="waves-effect waves-light btn modal-trigger red darken-1" href="#modal-<%=blog.title%>">Delete</a>
    </td>
  </tr>
   <% end %>
</tbody>
</table>


<% @blogs.each do |blog| %>
<div id="modal-<%= blog.title%>" class="modal">
   <div class="modal-content">
     <h4>Are you sure you want to delete "<%=blog.title%>"?</h4>
     <p>This action cannot be undone.</p>
   </div>
   <div class="modal-footer">
     <%= button_to "delete",
     {:controller => :blogs,:action => 'destroy', :id => blog.id },
     :method => :delete, :class => " modal-action modal-close waves-effect waves-green btn-flat" %>
     <!-- <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">DELETE</a> -->
   </div>
 </div>
 <% end %>

app/views/blogs/new.html.erb
<h1>New Post</h1>

<h6><%= link_to "Back to your posts", blogs_path %></h6>
<%= render 'new_blog' %>

app/views/blogs/show.html.erb
<div class="individual-post">
  <div class="parallax-container">
    <div class="parallax">
      <img src="<%= @blog.header_image %>" alt="" />
    </div>
  </div>
  <h1><%= @blog.title %> </h1>
  <h6><<%= @blog.created_at.strftime("%B %d, %Y") %> </h6>
  <h6>By Liina Edun</h6>
  <div class="section">
    <p>
      <%= @blog.message.html_safe %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MinimalisticTravel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar">
  <nav>
    <div class="nav-wrapper teal accent-4">
      <a href="/" class="brand-logo">&nbsp; Minimalistic Travel</a>
      <ul class="right hide-on-med-and-down">
      </ul>
    </div>
  </nav>
</div>

<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="post-list">
  <div class="row">
    <% @blogs.each_with_index do |blog, index| %>
      <% if index == 0 %>
        <a href="/blogs/<%= blog.id %>">
          <div class="col s12 featured-post">
            <div class="featured-image-container">
              <img src="<%= blog.header_image %>" alt="" />
            </div>
            <h2 class="post-title">
              <%= blog.title %>
              <div class="post-date">
                <%= blog.created_at.strftime("%B %d, %Y") %>
              </div>
            </h2>
            <h6 class="post-tagline">
              <%= blog.tagline %>
            </h5>
          </div>
        </a>

      <% elsif index > 0 && index % 2 != 0 %>
        <a href="/blogs/<%= blog.id %>">
          <div class="col s12 m6 post">
            <div class="blog-image-container">
              <img src="<%= blog.header_image %>" />
            </div>
            <h2 class="post-title">
              <%= blog.title %>
              <div class="post-date">
                <%= blog.created_at.strftime("%B %d, %Y") %>
              </div>
            </h2>
            <h6 class="post-tagline">
              <%= blog.tagline %>
            </h5>
          </div>
        </a>

      <% elsif index > 0 && index % 2 == 0 %>
        <a href="/blogs/<%= blog.id %>">
          <div class="col s12 m6 post">
            <div class="blog-image-container">
              <img src="<%= blog.header_image %>" />
            </div>
            <h2 class="post-title">
              <%= blog.title %>
              <div class="post-date">
                <%= blog.created_at.strftime("%B %d, %Y") %>
              </div>
            </h2>
            <h6 class="post-tagline">
              <%= blog.tagline %>
            </h5>
          </div>
        </a>
      <% end %>
    <% end %>
  </div>
</div>